Learning_Users/Basic_App/urls.py
from django.conf.urls import url
from Basic_App import views

# Template URLs

app_name = 'Basic_App'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

Learning_Users/Learning_Users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from Basic_App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^Basic_App/', include('Basic_App.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),
]

Learning_Users/Basic_App/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additonal classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

def __str__(self):
    return self.user.username

Learning_Users/Basic_App/forms.py
from django import forms
from django.contrib.auth.models import User
from Basic_App.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic',)

Learning_Users/Basic_App/views.py
from django.shortcuts import render
from Basic_App.forms import UserForm, UserProfileInfoForm

# Login Requirements
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'Basic_App/index.html')

@login_required
def special(request):
    return HttpResponse("Your are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # Do not save at first to avoid data collisions, first add a user to profile object, then check for pic and save after
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = {
    'user_form': user_form,
    'profile_form':profile_form,
    'registered':registered,
    }

    return render(request, 'Basic_App/registration.html',context)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("This was a failed login attempt")
            print("Username {} and password {}".format(username,password))
            return HttpResponse("Invalid Login Details Provided")
    else:
        return render(request, 'Basic_App/login.html', {})

Learning_Users/templates/Basic_App/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class='navbar navbar-dark bg-dark'>
      <div class="container">
        <div class='navbar-nav'>
          <a class='navbar-brand' href="{% url 'index'%}">Home Page</a>
          <a class='navbar-item nav-link' href="{% url 'admin:index'%}">Admin</a>
          <a class='navbar-item nav-link' href="{% url 'Basic_App:register' %}">Register</a>
          {% if user.is_authenticated %}
            <a class="navbar-item nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a class="navbar-item nav-link" href="{% url 'Basic_App:user_login' %}">Login</a>
          {% endif %}

        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}{% endblock %}
    </div>

  </body>
</html>

Learning_Users/templates/Basic_App/index.html
{% extends "Basic_App/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django Level Five</h1>
  </div>

{% endblock body_block %}

Learning_Users/templates/Basic_App/login.html
{% extends "Basic_App/base.html" %}
{% block  body_block%}

  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'Basic_App:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" value="Enter Username">

      <label for="password">Password:</label>
      <input type="text" name="password" value="Enter Password">

      <input type="submit" name="" value="Login">
    </form>
  </div>

{% endblock %}

Learning_Users/templates/Basic_App/registration.html
{% extends "Basic_App/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Register now</h1>
      <h3>Fill out the registration form</h3>
      {# <pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre> #}
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}

  </div>
{% endblock body_block %}